# ID and Account Information
"Deal : ID": "Deal : id"
"Deal : AccountName": "Deal : Account name"
"Deal : Name": "Deal : Name"
"Deal : Owner": "Deal : Owner"
"Deal : Source": "Deal : Source"

# Deal Stages, Probability, and Values
"Deal : DealStage": "Deal : Deal stage"
"Deal : Probability": "Deal : Probability (%)"
"Deal : ExpectedCloseDate": "Deal : Expected close date"
"Deal : DealValue": "Deal : Total Deal Value"
"Deal : TotalCost": "Deal : Total Cost"
"Deal : GrossMargin": "Deal : Gross Margin (GM)"
"Deal : Age": "Deal : Age (in days)"
"Deal : ClosedDate": "Deal : Closed date"

# Dates and Project Details
"Deal : TentativeStartDateMSD": "Deal : Tentative start date/MSD"
"Deal : ExpectedGoLiveDateMED": "Deal : Expected go live date/MED"
"Deal : ProjectType": "Deal : Project type"
"Deal : TypeOfRenewal": "Deal : Type of Renewal"
"Deal : AccorSaaSOnboarding": "Deal : Accor SaaS onboarding"
"Deal : ProjectScope": "Deal : Project Scope"
"Deal : ForecastCategory": "Deal : Forecast category"
"Deal : ProjectCode": "Deal : Project Code"
"Deal : ImplementationType": "Deal : Implementation type"
"Deal : ProjectLocation": "Deal : Project Location"
"Deal : CreatedAt": "Deal : Created at"

# Product 1 Mappings
"Deal : Product1": "Deal : Product 1"
"Deal : SoftwareRevenueProduct1": "Deal : Software revenue: Product 1"
"Deal : ServiceRevenueProduct1": "Deal : Service revenue: Product 1"
"Deal : ServiceDaysProduct1": "Deal : Cons days: Product 1"
"Deal : PMDaysProduct1": "Deal : PM days: Product 1"
"Deal : PAAdminDaysProduct1": "Deal : PA days: Product 1"
"Deal : TechnicalDaysProduct1": "Deal : Technical days: Product 1"
"Deal : SoftwareCostProduct1": "Deal : Software cost: Product 1"
"Deal : SupportRevenueProduct1": "Deal : Support revenue: Product 1"
"Deal : SupportCostProduct1": "Deal : Support cost: Product 1"
"Deal : ServiceCostProduct1": "Deal : Service cost: Product 1"
"Deal : HostingRevenueProduct1": "Deal : Hosting revenue: Product 1"
"Deal : ManagedServiceRevenueProduct1": "Deal : Managed service revenue: Product 1"
"Deal : ManagedServiceCostProduct1": "Deal : Managed service cost: Product 1"

# Product 2 Mappings
"Deal : Product2": "Deal : Product 2"
"Deal : SoftwareRevenueProduct2": "Deal : Software revenue: Product 2"
"Deal : ServiceRevenueProduct2": "Deal : Service revenue: Product 2"
"Deal : ServiceDaysProduct2": "Deal : Cons days: Product 2"
"Deal : PMDaysProduct2": "Deal : PM days: Product 2"
"Deal : PAAdminDaysProduct2": "Deal : PA days: Product 2"
"Deal : TechnicalDaysProduct2": "Deal : Technical days: Product 2"
"Deal : SoftwareCostProduct2": "Deal : Software cost: Product 2"
"Deal : SupportRevenueProduct2": "Deal : Support revenue: Product 2"
"Deal : SupportCostProduct2": "Deal : Support cost: Product 2"
"Deal : ServiceCostProduct2": "Deal : Service cost: Product 2"
"Deal : HostingRevenueProduct2": "Deal : Hosting revenue: Product 2"
"Deal : ManagedServiceRevenueProduct2": "Deal : Managed service revenue: Product 2"
"Deal : ManagedServiceCostProduct2": "Deal : Managed service cost: Product 2"

# Product 3 Mappings
"Deal : Product3": "Deal : Product 3"
"Deal : SoftwareRevenueProduct3": "Deal : Software revenue: Product 3"
"Deal : ServiceRevenueProduct3": "Deal : Service revenue: Product 3"
"Deal : ServiceDaysProduct3": "Deal : Cons days: Product 3"
"Deal : PMDaysProduct3": "Deal : PM days: Product 3"
"Deal : PAAdminDaysProduct3": "Deal : PA days: Product 3"
"Deal : TechnicalDaysProduct3": "Deal : Technical days: Product 3"
"Deal : SoftwareCostProduct3": "Deal : Software cost: Product 3"
"Deal : SupportRevenueProduct3": "Deal : Support revenue: Product 3"
"Deal : SupportCostProduct3": "Deal : Support cost: Product 3"
"Deal : ServiceCostProduct3": "Deal : Service cost: Product 3"
"Deal : HostingRevenueProduct3": "Deal : Hosting revenue: Product 3"
"Deal : ManagedServiceRevenueProduct3": "Deal : Managed service revenue: Product 3"
"Deal : ManagedServiceCostProduct3": "Deal : Managed service cost: Product 3"

# Product 4 Mappings
"Deal : Product4": "Deal : Product 4"
"Deal : SoftwareRevenueProduct4": "Deal : Software revenue: Product 4"
"Deal : ServiceRevenueProduct4": "Deal : Service revenue: Product 4"
"Deal : ConsDaysProduct4": "Deal : Cons days: Product 4"
"Deal : PMDaysProduct4": "Deal : PM days: Product 4"
"Deal : PAAdminDaysProduct4": "Deal : PA days: Product 4"
"Deal : TechnicalDaysProduct4": "Deal : Technical days: Product 4"
"Deal : SoftwareCostProduct4": "Deal : Software cost: Product 4"
"Deal : SupportRevenueProduct4": "Deal : Support revenue: Product 4"
"Deal : SupportCostProduct4": "Deal : Support cost: Product 4"
"Deal : ServiceCostProduct4": "Deal : Service cost: Product 4"
"Deal : HostingRevenueProduct4": "Deal : Hosting revenue: Product 4"
"Deal : ManagedServiceRevenueProduct4": "Deal : Managed service revenue: Product 4"
"Deal : ManagedServiceCostProduct4": "Deal : Managed service cost: Product 4"
