revenue_targets:
  Le Thi Hong Nhung: 700000
  Nguyet Vo: 560000
  Sarocha Pimthong: 625000
  Linh Tran: 800000
  Quynh Nhu Tran: 800000
  Vo Ly Ngoc Han: 700000
  Mai Nguyen: 600000
  Andrew Richard Turton: 1000000
  Le Hoang Minh Trang: 560000

deal_type:
  NonRecurring: 4700000
  Recurring: 1600000
  AllDeal: 6300000
